tracked_extensions:
  - .py
  - .ipynb
  - .json
  - .yaml
  - .txt
  - .toml
  -  pdf
  - .md
  

text_extensions:
  - .txt
  - .md
  - .csv
  - .tsv
  - .json
  - .yaml
  - .py
  - .ipynb
  - .toml
  - .cfg
  - .gif
  - .png
  - .zip


ignored_names:
  - .env
  - .venv
  - venv
  - env
  - model_inputs_outputs
  - .git
  - .ipynb_checkpoints
  - __pycache__
  - __init__.py